/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppProjectIdRouteImport } from './routes/app.$projectId'
import { Route as AppTaskTaskIdRouteImport } from './routes/app.task.$taskId'
import { Route as ApiTasksTaskIdRunRouteImport } from './routes/api.tasks.$taskId.run'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectIdRoute = AppProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => AppRoute,
} as any)
const AppTaskTaskIdRoute = AppTaskTaskIdRouteImport.update({
  id: '/task/$taskId',
  path: '/task/$taskId',
  getParentRoute: () => AppRoute,
} as any)
const ApiTasksTaskIdRunRoute = ApiTasksTaskIdRunRouteImport.update({
  id: '/api/tasks/$taskId/run',
  path: '/api/tasks/$taskId/run',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/$projectId': typeof AppProjectIdRoute
  '/app/': typeof AppIndexRoute
  '/app/task/$taskId': typeof AppTaskTaskIdRoute
  '/api/tasks/$taskId/run': typeof ApiTasksTaskIdRunRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/$projectId': typeof AppProjectIdRoute
  '/app': typeof AppIndexRoute
  '/app/task/$taskId': typeof AppTaskTaskIdRoute
  '/api/tasks/$taskId/run': typeof ApiTasksTaskIdRunRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/$projectId': typeof AppProjectIdRoute
  '/app/': typeof AppIndexRoute
  '/app/task/$taskId': typeof AppTaskTaskIdRoute
  '/api/tasks/$taskId/run': typeof ApiTasksTaskIdRunRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/$projectId'
    | '/app/'
    | '/app/task/$taskId'
    | '/api/tasks/$taskId/run'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/$projectId'
    | '/app'
    | '/app/task/$taskId'
    | '/api/tasks/$taskId/run'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/$projectId'
    | '/app/'
    | '/app/task/$taskId'
    | '/api/tasks/$taskId/run'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ApiTasksTaskIdRunRoute: typeof ApiTasksTaskIdRunRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/$projectId': {
      id: '/app/$projectId'
      path: '/$projectId'
      fullPath: '/app/$projectId'
      preLoaderRoute: typeof AppProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/task/$taskId': {
      id: '/app/task/$taskId'
      path: '/task/$taskId'
      fullPath: '/app/task/$taskId'
      preLoaderRoute: typeof AppTaskTaskIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/tasks/$taskId/run': {
      id: '/api/tasks/$taskId/run'
      path: '/api/tasks/$taskId/run'
      fullPath: '/api/tasks/$taskId/run'
      preLoaderRoute: typeof ApiTasksTaskIdRunRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppProjectIdRoute: typeof AppProjectIdRoute
  AppIndexRoute: typeof AppIndexRoute
  AppTaskTaskIdRoute: typeof AppTaskTaskIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppProjectIdRoute: AppProjectIdRoute,
  AppIndexRoute: AppIndexRoute,
  AppTaskTaskIdRoute: AppTaskTaskIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ApiTasksTaskIdRunRoute: ApiTasksTaskIdRunRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
